// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//

using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;

namespace CCR {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=false)]
    public class ContinuityOfCareRecord {
        
        /// <remarks/>
        public string CCRDocumentObjectID;
        
        /// <remarks/>
        public CodedDescriptionType Language;
        
        /// <remarks/>
        public string Version;
        
        /// <remarks/>
        public DateTimeType DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Patient")]
        public List<ContinuityOfCareRecordPatient> Patient;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="ActorLink", IsNullable=false)]
        public List<ActorReferenceType> From;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="ActorLink", IsNullable=false)]
        public List<ActorReferenceType> To;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Purpose")]
        public List<PurposeType> Purpose;
        
        /// <remarks/>
        public ContinuityOfCareRecordBody Body;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Actor", IsNullable=false)]
        public List<ActorType> Actors;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Reference", IsNullable=false)]
        public List<ReferenceType> References;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Comment", IsNullable=false)]
        public List<CommentType> Comments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="CCRSignature", IsNullable=false)]
        public List<SignatureType> Signatures;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute("Description", Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SiteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductTypeProductForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductTypeProductSize))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionRoute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleTypeProductForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleTypeProductSize))]
    public class CodedDescriptionType {
        
        /// <remarks/>
        public string Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectAttribute")]
        public List<CodedDescriptionTypeObjectAttribute> ObjectAttribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CodedDescriptionTypeObjectAttribute {
        
        /// <remarks/>
        public string Attribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeValue")]
        public List<CodedDescriptionTypeObjectAttributeAttributeValue> AttributeValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CodedDescriptionTypeObjectAttributeAttributeValue {
        
        /// <remarks/>
        public object Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionAdministrationTiming))]
    public class DateTimeType {
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public string ExactDateTime;
        
        /// <remarks/>
        public MeasureType Age;
        
        /// <remarks/>
        public CodedDescriptionType ApproximateDateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTimeRange")]
        public List<DateTimeTypeDateTimeRange> DateTimeRange;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute("Age", Namespace="urn:astm-org:CCR", IsNullable=true)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QuantityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndicationTypePhysiologicalParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoseCalculationTypeVariable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleTypeQuantity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductTypeProductStrength))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductTypeProductConcentration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionDose))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleTypeProductStrength))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleTypeProductConcentration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductTypeProductSizeDimensionsDimension))]
    public class MeasureType {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public MeasureTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class MeasureTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CodeType {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public string CodingSystem;
        
        /// <remarks/>
        public string Version;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class QuantityType : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QuantitySequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableQuantityModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IndicationTypePhysiologicalParameter : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ParameterSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableParameterModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DoseCalculationTypeVariable : MeasureType {
        
        /// <remarks/>
        public string VariableIdentifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VariableSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeQuantity : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QuantitySequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableQuantityModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProductStrength : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string StrengthSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableStrengthModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProductConcentration : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConcentrationSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableConcentrationModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DirectionDose : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rate")]
        public List<RateType> Rate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DoseSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableDoseModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class RateType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public RateTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RateSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableRateModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class RateTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeProductStrength : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string StrengthSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableStrengthModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeProductConcentration : MeasureType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConcentrationSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableConcentrationModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProductSizeDimensionsDimension : MeasureType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DateTimeTypeDateTimeRange {
        
        /// <remarks/>
        public DateTimeTypeDateTimeRangeBeginRange BeginRange;
        
        /// <remarks/>
        public DateTimeTypeDateTimeRangeEndRange EndRange;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DateTimeTypeDateTimeRangeBeginRange {
        
        /// <remarks/>
        public string ExactDateTime;
        
        /// <remarks/>
        public MeasureType Age;
        
        /// <remarks/>
        public CodedDescriptionType ApproximateDateTime;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DateTimeTypeDateTimeRangeEndRange {
        
        /// <remarks/>
        public string ExactDateTime;
        
        /// <remarks/>
        public MeasureType Age;
        
        /// <remarks/>
        public CodedDescriptionType ApproximateDateTime;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DirectionAdministrationTiming : DateTimeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TimingSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableTimingModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ContinuityOfCareRecordPatient {
        
        /// <remarks/>
        public string ActorID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute("Actor", Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyHistoryTypeFamilyMember))]
    public class ActorReferenceType {
        
        /// <remarks/>
        public string ActorID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActorRole")]
        public List<CodedDescriptionType> ActorRole;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FamilyHistoryTypeFamilyMember : ActorReferenceType {
        
        /// <remarks/>
        public CurrentHealthStatusType HealthStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<FamilyHistoryTypeFamilyMemberSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CurrentHealthStatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public string CauseOfDeath;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<CurrentHealthStatusTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalCCRLinkSource))]
    public class SourceType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Actor")]
        public List<ActorReferenceType> Actor;
        
        /// <remarks/>
        public DateTimeType DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class InternalCCRLinkSource : SourceType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class InternalCCRLink {
        
        /// <remarks/>
        public string LinkID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinkRelationship")]
        public List<string> LinkRelationship;
        
        /// <remarks/>
        public InternalCCRLinkSource Source;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CurrentHealthStatusTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FamilyHistoryTypeFamilyMemberSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PurposeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public List<CodedDescriptionType> Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderRequest")]
        public List<PlanOfCareType> OrderRequest;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Indications")]
        public List<IndicationType> Indications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PlanOfCareType : InterventionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Goal", IsNullable=false)]
        public List<GoalType> Goals;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string OrderSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleOrderModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class GoalType : EncounterType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Outcome", IsNullable=false)]
        public List<CCRCodedDataObjectType> Milestones;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterventionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanOfCareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsuranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProblemType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyHistoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SocialHistoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AlertType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredProductType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EncounterType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GoalType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthorizationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EpisodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderRxHistoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TestType))]
    public class CCRCodedDataObjectType {
        
        /// <remarks/>
        public string CCRDataObjectID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDs")]
        public List<IDType> IDs;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<CCRCodedDataObjectTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute("IDs", Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class IDType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public ActorReferenceType IssuedBy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<IDTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IDTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CCRCodedDataObjectTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanOfCareType))]
    public class InterventionType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Procedure", IsNullable=false)]
        public List<ProcedureType> Procedures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Products;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Medication", IsNullable=false)]
        public List<StructuredProductType> Medications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Immunization", IsNullable=false)]
        public List<StructuredProductType> Immunizations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Service", IsNullable=false)]
        public List<EncounterType> Services;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Encounters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Authorization", IsNullable=false)]
        public List<AuthorizationType> Authorizatons;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ProcedureType {
        
        /// <remarks/>
        public string CCRDataObjectID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public IDType IDs;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<ProcedureTypeSignature> Signature;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public List<Location> Locations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Practitioner", IsNullable=false)]
        public List<ActorReferenceType> Practitioners;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Frequency")]
        public List<FrequencyType> Frequency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Interval")]
        public List<IntervalType> Interval;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Duration")]
        public List<DurationType> Duration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Indications")]
        public List<IndicationType> Indications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Instruction", IsNullable=false)]
        public List<CodedDescriptionType> Instructions;
        
        /// <remarks/>
        public CCRCodedDataObjectType Consent;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Products;
        
        /// <remarks/>
        public CodedDescriptionType Substance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public List<MethodType> Method;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public List<PositionType> Position;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Site")]
        public List<SiteType> Site;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ProcedureTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class Location {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public ActorReferenceType Actor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FrequencyType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public FrequencyTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FrequencySequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableFrequencyModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FrequencyTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IntervalType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public IntervalTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IntervalSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableIntervalModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IntervalTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DurationType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public DurationTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DurationSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableDurationModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DurationTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IndicationType {
        
        /// <remarks/>
        public CodedDescriptionType PRNFlag;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public List<CodedDescriptionType> Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Problem")]
        public List<ProblemType> Problem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhysiologicalParameter")]
        public List<IndicationTypePhysiologicalParameter> PhysiologicalParameter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<IndicationTypeSignature> Signature;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IndicationSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleIndicationModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ProblemType : CCRCodedDataObjectType {
        
        /// <remarks/>
        public EpisodesType Episodes;
        
        /// <remarks/>
        public CurrentHealthStatusType HealthStatus;
        
        /// <remarks/>
        public PatientKnowledgeType PatientKnowledge;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class EpisodesType {
        
        /// <remarks/>
        public string Number;
        
        /// <remarks/>
        public MeasureType Frequency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Episode")]
        public List<EpisodeType> Episode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<EpisodesTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class EpisodeType : CCRCodedDataObjectType {
        
        /// <remarks/>
        public DurationType Duration;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class EpisodesTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PatientKnowledgeType {
        
        /// <remarks/>
        public string PatientAware;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<PatientKnowledgeTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PatientKnowledgeTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class IndicationTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product")]
        public List<StructuredProductTypeProduct> Product;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public List<QuantityType> Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public List<Direction> Directions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Instruction", IsNullable=false)]
        public List<InstructionType> PatientInstructions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Instruction", IsNullable=false)]
        public List<InstructionType> FulfillmentInstructions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Refill", IsNullable=false)]
        public List<StructuredProductTypeRefillsRefill> Refills;
        
        /// <remarks/>
        public string SeriesNumber;
        
        /// <remarks/>
        public CCRCodedDataObjectType Consent;
        
        /// <remarks/>
        public Reaction Reaction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Fulfillment", IsNullable=false)]
        public List<OrderRxHistoryType> FulfillmentHistory;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProduct {
        
        /// <remarks/>
        public CodedDescriptionType ProductName;
        
        /// <remarks/>
        public CodedDescriptionType BrandName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strength")]
        public List<StructuredProductTypeProductStrength> Strength;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Form")]
        public List<StructuredProductTypeProductForm> Form;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Concentration")]
        public List<StructuredProductTypeProductConcentration> Concentration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size")]
        public List<StructuredProductTypeProductSize> Size;
        
        /// <remarks/>
        public ActorReferenceType Manufacturer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ProductSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleProductModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProductForm : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FormSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleFormModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeProductSize : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Dimension", IsNullable=false)]
        public List<StructuredProductTypeProductSizeDimensionsDimension> Dimensions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SizeSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableSizeModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class Direction {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType DoseIndicator;
        
        /// <remarks/>
        public CodedDescriptionType DeliveryMethod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dose")]
        public List<DirectionDose> Dose;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoseCalculation")]
        public List<DirectionDoseCalculation> DoseCalculation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vehicle")]
        public List<VehicleType> Vehicle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Route")]
        public List<DirectionRoute> Route;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Site")]
        public List<SiteType> Site;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdministrationTiming")]
        public List<DirectionAdministrationTiming> AdministrationTiming;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Frequency")]
        public List<FrequencyType> Frequency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Interval")]
        public List<IntervalType> Interval;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Duration")]
        public List<DurationType> Duration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoseRestriction")]
        public List<DirectionDoseRestriction> DoseRestriction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Indication")]
        public List<IndicationType> Indication;
        
        /// <remarks/>
        public CodedDescriptionType StopIndicator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DirectionSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleDirectionModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DirectionDoseCalculation : DoseCalculationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rate")]
        public List<RateType> Rate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CalculationSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableCalculationModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionDoseCalculation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionDoseRestriction))]
    public class DoseCalculationType {
        
        /// <remarks/>
        public MeasureType Dose;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variable")]
        public List<DoseCalculationTypeVariable> Variable;
        
        /// <remarks/>
        public DoseCalculationTypeCalculationEquation CalculationEquation;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DoseCalculationTypeCalculationEquation {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DirectionDoseRestriction : DoseCalculationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rate")]
        public List<RateType> Rate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RestrictionSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableRestrictionModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product")]
        public List<VehicleTypeProduct> Product;
        
        /// <remarks/>
        public ActorReferenceType Manufacturer;
        
        /// <remarks/>
        public IDType IDs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public List<VehicleTypeQuantity> Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VehicleSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleVehicleModifier;
        
        /// <remarks/>
        public InternalCCRLink InternalCCRLink;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeProduct {
        
        /// <remarks/>
        public CodedDescriptionType ProductName;
        
        /// <remarks/>
        public CodedDescriptionType BrandName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strength")]
        public List<VehicleTypeProductStrength> Strength;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Form")]
        public List<VehicleTypeProductForm> Form;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Concentration")]
        public List<VehicleTypeProductConcentration> Concentration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size")]
        public List<VehicleTypeProductSize> Size;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ProductSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleProductModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeProductForm : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FormSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleFormModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class VehicleTypeProductSize : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SizeSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableSizeModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class DirectionRoute : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RouteSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleRouteModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class SiteType : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SiteSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleSiteModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class InstructionType : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string instructionSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleInstructionModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class StructuredProductTypeRefillsRefill {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Number", DataType="integer")]
        public List<string> Number;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public List<QuantityType> Quantity;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comment")]
        public List<CommentType> Comment;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CommentType {
        
        /// <remarks/>
        public string CommentObjectID;
        
        /// <remarks/>
        public DateTimeType DateTime;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<ActorReferenceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class Reaction {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        public CodedDescriptionType Severity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Intervention", IsNullable=false)]
        public List<ReactionInterventionsIntervention> Interventions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReactionSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleReactionModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ReactionInterventionsIntervention {
        
        /// <remarks/>
        public string CCRDataObjectID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<ReactionInterventionsInterventionSignature> Signature;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Procedure", IsNullable=false)]
        public List<ProcedureType> Procedures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Products;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Medications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Immunization", IsNullable=false)]
        public List<StructuredProductType> Immunizations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Services;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Encounters;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ReactionInterventionsInterventionSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GoalType))]
    public class EncounterType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public List<Location> Locations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Practitioner", IsNullable=false)]
        public List<ActorReferenceType> Practitioners;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Frequency")]
        public List<FrequencyType> Frequency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Interval")]
        public List<IntervalType> Interval;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Duration")]
        public List<DurationType> Duration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Indication", IsNullable=false)]
        public List<IndicationType> Indications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Instruction", IsNullable=false)]
        public List<CodedDescriptionType> Instructions;
        
        /// <remarks/>
        public CCRCodedDataObjectType Consent;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class OrderRxHistoryType : CCRCodedDataObjectType {
        
        /// <remarks/>
        public CodedDescriptionType FulfillmentMethod;
        
        /// <remarks/>
        public ActorReferenceType Provider;
        
        /// <remarks/>
        public ActorReferenceType Location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reaction")]
        public List<Reaction> Reaction;
        
        /// <remarks/>
        public CodedDescriptionType ProductName;
        
        /// <remarks/>
        public string BrandName;
        
        /// <remarks/>
        public ActorReferenceType Manufacturer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strength")]
        public List<MeasureType> Strength;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Form")]
        public List<CodedDescriptionType> Form;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Concentration")]
        public List<MeasureType> Concentration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public List<MeasureType> Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LabelInstructions")]
        public List<InstructionType> LabelInstructions;
        
        /// <remarks/>
        public string SeriesNumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class MethodType : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MethodSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultipleMethodModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PositionType : CodedDescriptionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PositionSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType MultiplePositionModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class AuthorizationType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Purpose")]
        public List<PurposeType> Purpose;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Practitioner", IsNullable=false)]
        public List<ActorReferenceType> Practitioners;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Procedure", IsNullable=false)]
        public List<ProcedureType> Procedures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Products;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Medication", IsNullable=false)]
        public List<StructuredProductType> Medications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Immunization", IsNullable=false)]
        public List<StructuredProductType> Immunizations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Services;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Encounters;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class InsuranceType : CCRCodedDataObjectType {
        
        /// <remarks/>
        public ActorReferenceType PaymentProvider;
        
        /// <remarks/>
        public ActorReferenceType Subscriber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Authorization", IsNullable=false)]
        public List<AuthorizationType> Authorizations;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FunctionType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Problem")]
        public List<ProblemType> Problem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Test")]
        public List<ResultType> Test;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ResultType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Procedure")]
        public List<ProcedureType> Procedure;
        
        /// <remarks/>
        public CodedDescriptionType Substance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Test")]
        public List<TestType> Test;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class TestType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public List<CodedDescriptionType> Method;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agent")]
        public List<Agent> Agent;
        
        /// <remarks/>
        public TestResultType TestResult;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Normal", IsNullable=false)]
        public List<NormalType> NormalResult;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flag")]
        public List<CodedDescriptionType> Flag;
        
        /// <remarks/>
        public CodedDescriptionType ConfidenceValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:astm-org:CCR", IsNullable=true)]
    public class Agent {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Product", IsNullable=false)]
        public List<StructuredProductType> Products;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="EnvironmentalAgent", IsNullable=false)]
        public List<CCRCodedDataObjectType> EnvironmentalAgents;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Problem", IsNullable=false)]
        public List<ProblemType> Problems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Procedure", IsNullable=false)]
        public List<ProcedureType> Procedures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Result", IsNullable=false)]
        public List<ResultType> Results;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class TestResultType {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public TestResultTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public List<CodedDescriptionType> Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ResultSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableResultModifier;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class TestResultTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class NormalType {
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public NormalTypeUnits Units;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ValueSequencePosition;
        
        /// <remarks/>
        public CodedDescriptionType VariableNormalModifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<NormalTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class NormalTypeUnits {
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public List<CodeType> Code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class NormalTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FamilyHistoryType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FamilyMember")]
        public List<FamilyHistoryTypeFamilyMember> FamilyMember;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Problem")]
        public List<FamilyHistoryTypeProblem> Problem;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FamilyHistoryTypeProblem {
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        public EpisodesType Episodes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<FamilyHistoryTypeProblemSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class FamilyHistoryTypeProblemSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class SocialHistoryType : CCRCodedDataObjectType {
        
        /// <remarks/>
        public EpisodesType Episodes;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class AlertType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agent")]
        public List<Agent> Agent;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reaction")]
        public List<Reaction> Reaction;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PlanType : CCRCodedDataObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderRequest")]
        public List<PlanOfCareType> OrderRequest;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ContinuityOfCareRecordBody {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Payer", IsNullable=false)]
        public List<InsuranceType> Payers;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="AdvanceDirective", IsNullable=false)]
        public List<CCRCodedDataObjectType> AdvanceDirectives;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="SupportProvider", IsNullable=false)]
        public List<ActorReferenceType> Support;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Function", IsNullable=false)]
        public List<FunctionType> FunctionalStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Problem", IsNullable=false)]
        public List<ProblemType> Problems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="FamilyProblemHistory", IsNullable=false)]
        public List<FamilyHistoryType> FamilyHistory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="SocialHistoryElement", IsNullable=false)]
        public List<SocialHistoryType> SocialHistory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Alert", IsNullable=false)]
        public List<AlertType> Alerts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Medication", IsNullable=false)]
        public List<StructuredProductType> Medications;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Equipment", IsNullable=false)]
        public List<StructuredProductType> MedicalEquipment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Immunization", IsNullable=false)]
        public List<StructuredProductType> Immunizations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Result", IsNullable=false)]
        public List<ResultType> VitalSigns;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Result", IsNullable=false)]
        public List<ResultType> Results;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Procedure", IsNullable=false)]
        public List<ProcedureType> Procedures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Encounter", IsNullable=false)]
        public List<EncounterType> Encounters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Plan", IsNullable=false)]
        public List<PlanType> PlanOfCare;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="Provider", IsNullable=false)]
        public List<ActorReferenceType> HealthCareProviders;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypeInformationSystem {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public string Version;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypeOrganization {
        
        /// <remarks/>
        public string Name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypePerson {
        
        /// <remarks/>
        public ActorTypePersonName Name;
        
        /// <remarks/>
        public DateTimeType DateOfBirth;
        
        /// <remarks/>
        public CodedDescriptionType Gender;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypePersonName {
        
        /// <remarks/>
        public PersonNameType BirthName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalName")]
        public List<PersonNameType> AdditionalName;
        
        /// <remarks/>
        public PersonNameType CurrentName;
        
        /// <remarks/>
        public string DisplayName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class PersonNameType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Given")]
        public List<string> Given;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Middle")]
        public List<string> Middle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Family")]
        public List<string> Family;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Suffix")]
        public List<string> Suffix;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public List<string> Title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NickName")]
        public List<object> NickName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorType {
        
        /// <remarks/>
        public string ActorObjectID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Person", Type=typeof(ActorTypePerson))]
        [System.Xml.Serialization.XmlElementAttribute("Organization", Type=typeof(ActorTypeOrganization))]
        [System.Xml.Serialization.XmlElementAttribute("InformationSystem", Type=typeof(ActorTypeInformationSystem))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDs")]
        public List<IDType> IDs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relation")]
        public List<CodedDescriptionType> Relation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Specialty")]
        public List<CodedDescriptionType> Specialty;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public List<ActorTypeAddress> Address;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Telephone")]
        public List<CommunicationType> Telephone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EMail")]
        public List<CommunicationType> EMail;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public List<CommunicationType> URL;
        
        /// <remarks/>
        public CodedDescriptionType Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<SourceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalCCRLink")]
        public List<InternalCCRLink> InternalCCRLink;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceID")]
        public List<string> ReferenceID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommentID")]
        public List<string> CommentID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public List<ActorTypeSignature> Signature;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypeAddress {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Preferred;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public string Line1;
        
        /// <remarks/>
        public string Line2;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string County;
        
        /// <remarks/>
        public string State;
        
        /// <remarks/>
        public string Country;
        
        /// <remarks/>
        public string PostalCode;
        
        /// <remarks/>
        public string Priority;
        
        /// <remarks/>
        public CodedDescriptionType Status;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class CommunicationType {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public string Priority;
        
        /// <remarks/>
        public CodedDescriptionType Status;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ActorTypeSignature {
        
        /// <remarks/>
        public string SignatureID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class ReferenceType {
        
        /// <remarks/>
        public string ReferenceObjectID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime")]
        public List<DateTimeType> DateTime;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        public CodedDescriptionType Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public List<ActorReferenceType> Source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public List<Location> Locations;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:astm-org:CCR")]
    public class SignatureType {
        
        /// <remarks/>
        public string SignatureObjectID;
        
        /// <remarks/>
        public string ExactDateTime;
        
        /// <remarks/>
        public CodedDescriptionType Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDs")]
        public List<IDType> IDs;
        
        /// <remarks/>
        public ActorReferenceType Source;
        
        /// <remarks/>
        public object Signature;
    }
}
